version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: portfolio-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - portfolio-network

  backend:
    build:
      context: ./portfolio-backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/portfolio_db?schema=public
      - JWT_SECRET=your_strong_secret_key_for_local_development
    volumes:
      - ./portfolio-backend:/app
      - /app/node_modules
    networks:
      - portfolio-network

  frontend:
    build:
      context: ./portfolio-frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    volumes:
      - ./portfolio-frontend:/app
      - /app/node_modules
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  postgres-data:
